name: ðŸš€ Deploy Spoko Sopot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host: 57.128.251.48
          username: debian
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 39222
          script: |
            set -e

            cd /home/debian/apps/spoko-sopot
            git pull https://github.com/EdwardTymoshuk/spoko-sopot.git main
            npm ci || npm install
            npm run build
            pm2 restart spoko-site || pm2 start npm --name "spoko-site" -- start
            pm2 save
